In [41]:
import numpy as np


In [42]:
a=np.array([1,2,4])

In [43]:
b=np.array([(1.7,3,4),(4,5,6)],dtype=float)

In [44]:
a

array([1, 2, 4])

In [45]:
b

array([[1.7, 3. , 4. ],
       [4. , 5. , 6. ]])

In [46]:
c=np.array([[(1.7,3,4),(4,5,6)], [(3,2,1),(4,5,6)]],dtype=float)

In [47]:
c

array([[[1.7, 3. , 4. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [48]:
d=np.zeros((3,4))

In [49]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
p = np.ones((2,3, 4))


In [51]:
p

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [52]:
p = np.ones((2, 3, 4), dtype=np.int16)

In [53]:
p

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [54]:
e=np.array((10,35,5))

In [55]:
e

array([10, 35,  5])

In [56]:
np.linspace(0, 3,10)


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [57]:
v=np.linspace(2, 2, 2)


In [58]:
v

array([2., 2.])

In [59]:
v


array([2., 2.])

In [60]:
x=np.linspace(2, 2, 7)

In [61]:
x

array([2., 2., 2., 2., 2., 2., 2.])

In [62]:
i=np.eye(2)

In [63]:
i

array([[1., 0.],
       [0., 1.]])

In [24]:
r=np.random.rand(2,2)

In [25]:
r

array([[0.33354516, 0.42252531],
       [0.96900127, 0.90243707]])

In [26]:
print("a -> shape:" ,a.shape, "ndim:", a.ndim, "size:", a.size)

a -> shape: (3,) ndim: 1 size: 3


In [27]:
print("b -> shape:" ,b.shape, "ndim:", b.ndim, "size:", b.size)

b -> shape: (2, 3) ndim: 2 size: 6


In [28]:
print("c -> shape:" ,c.shape, "ndim:", c.ndim, "size:", c.size)

c -> shape: (2, 2, 3) ndim: 3 size: 12


In [29]:
print("b dtype:" , b.dtype)
print("b dtype:" , b.dtype.name)
b_int=b.astype(int)
print("b converted to int :\n", b_int)

b dtype: float64
b dtype: float64
b converted to int :
 [[1 2 3]
 [4 5 6]]


In [30]:
print("b * b:\n", b*b)

b * b:
 [[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]


In [31]:
print("b * b:\n", b/b)

b * b:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
b=np.sqrt(b)

In [33]:
b

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
m=np.array([1,9,6])


In [35]:
np.sum(m)

np.int32(16)

In [36]:
np.min(m)

np.int32(1)

In [37]:
np.median(m)

np.float64(6.0)

In [38]:
np.mean(m)


np.float64(5.333333333333333)

In [39]:
np.cumsum(m)



array([ 1, 10, 16])

In [40]:
np.std(m)


np.float64(3.2998316455372216)